"""Add question_type, options, correct_answer to interview_questions

Revision ID: 76dee69f4758
Revises: 0dcba311031e
Create Date: 2026-08-24 20:32:33.243648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76dee69f4758'
down_revision: Union[str, None] = '0dcba311031e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_questions', sa.Column('question_type', sa.String(length=50), nullable=False, server_default='text'))
    op.add_column('interview_questions', sa.Column('options', sa.JSON(), nullable=True))
    op.add_column('interview_questions', sa.Column('correct_answer', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_questions', 'correct_answer')
    op.drop_column('interview_questions', 'options')
    op.drop_column('interview_questions', 'question_type')
    # ### end Alembic commands ###
